//
//  CoinsListWorker.swift
//  MarketingCoins
//
//  Created by Gabriel Felix on 31/10/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CoinsListWorker
{
  func doSomeWork()
  {
  }
}
