//
//  CoinsListModels.swift
//  MarketingCoins
//
//  Created by Gabriel Felix on 31/10/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CoinsList {
  // MARK: Use cases
  
  enum FetchGlobalValues {
    
        struct Request {
            let baseCoin: String
        }
          
        struct Response {
            let baseCoin: String
            let totalMarketCap: [String: String]
            let totalVolume: [String: String]
        }
        struct ViewModel {
            struct GlobalValues {
                let title: String
                let value: String
            }
            let globalValues: [GlobalValues]
        }
    }
    
    enum FetchCoinsList {
        
        struct Request {
            let baseCoin: String
            let orderBy: String
            let top: Int
            let pricePercentage: String
        }
        
        struct Response {
            let baseCoin: String
            let id: String
            let symbol: String
        }
        struct ViewModel: Decodable {
            
        }
    }
}
