//
//  CoinsListWorker.swift
//  MarketingCoins
//
//  Created by Gabriel Felix on 31/10/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CoinsListWorker {
    
    private let dataProvider: CoinListDataProvider?
    private var completion: ((Result<[CoinModel]?, CryptocurrenciesError>) -> Void)?
    
    init(dataProvider: CoinListDataProvider = CoinListDataProvider(coinsStore: CoinStore())) {
        self.dataProvider = dataProvider
        self.dataProvider?.delegate = self
    }
    
    func doFetchListCoins(baseCoin: String,
                          orderBy: String,
                          top: Int,
                          percentagePrice: String,
                          completion: @escaping (Result<[CoinModel]?, CryptocurrenciesError>) -> Void) {
        self.completion = completion
        dataProvider?.fetchListCoins(by: baseCoin,
                                     with: nil,
                                     orderBy: orderBy,
                                     total: top,
                                     page: 1,
                                     percentagePrice: percentagePrice)
    }
}

// MARK: - ListCoinDataProviderDelegate
extension CoinsListWorker: CoinListDataProviderDelegate {
    
    func success(model: Any) {
        guard let completion = completion else {
            fatalError("Completion not implemented!")
        }
        completion(.success(model as? [CoinModel]))
    }
    
    func errorData(_ provider: GenericDataProviderDelegate?, error: Error) {
        guard let completion = completion else {
            fatalError("Completion not implemented!")
        }
        
        let nsError = error as NSError
        switch nsError.code {
        case 500:
            completion(.failure(.internalServerError))
        case 400:
            completion(.failure(.badRequestError))
        case 404:
            completion(.failure(.notFoundError))
        default:
            completion(.failure(.undefinedError))
        }
    }
}
