//
//  CoinsListInteractor.swift
//  MarketingCoins
//
//  Created by Gabriel Felix on 31/10/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CoinsListBusinessLogic {
    func doFetchGlobalValues(request: CoinsList.FetchGlobalValues.Request)
    func doFetchListCoins(request: CoinsList.FetchCoinsList.Request)
}

protocol CoinsListDataStore {
  //var name: String { get set }
}

class CoinsListInteractor: CoinsListBusinessLogic, CoinsListDataStore {
    
    var presenter: CoinsListPresentationLogic?
    var globalValuesWorker: GlobalValuesWorker?
    var coinListWorker: CoinsListWorker?
    
    init(presenter: CoinsListPresentationLogic = CoinsListPresenter(),
         globalValuesWorker: GlobalValuesWorker = GlobalValuesWorker(),
         coinListWorker: CoinsListWorker? = CoinsListWorker()) {
        
        self.presenter = presenter
        self.globalValuesWorker = globalValuesWorker
        self.coinListWorker = coinListWorker
    }
    
    func doFetchGlobalValues(request: CoinsList.FetchGlobalValues.Request) {
        globalValuesWorker?.doFetchGlobalValues(completion: { result in
            switch result {
            case .success(let globalModel):
                self.createGlobalValuesResponse(baseCoin: request.baseCoin, globalModel: globalModel)
            case .failure(let error):
                
            }
        })
    }
    
    func doFetchListCoins(request: CoinsList.FetchCoinsList.Request) {
        
        let baseCoin = request.baseCoin
        let orderBy = request.orderBy
        let top = request.top
        let percetagePrice = request.pricePercentage
        
        coinListWorker?.doFetchListCoins(baseCoin: baseCoin,
                                         orderBy: orderBy,
                                         top: top,
                                         percentagePrice: percetagePrice,
                                         completion: { result in
            switch result {
            case .success(let globalModel):
            case .failure(let error):
            }
        })
    }
    private func createGlobalValuesResponse(baseCoin: String, globalModel: GlobalModel?) {
        if let globalModel {
            let totalMarketCap = globalModel.data.totalMarketCap.filter{ $0.key == baseCoin }
            let totalVolume = globalModel.data.totalVolume.filter{ $0.key == baseCoin }
            
            let response = CoinsList.FetchGlobalValues.Response(
                baseCoin: baseCoin,
                totalMarketCap: totalMarketCap,
                totalVolume: totalVolume)
        } else {
            print("")
        }
    }
    
    private func createListCoinsResponse(request: CoinsList.FetchCoinsList.Request, listCoins: [CoinModel]?) {
        if let listCoins {
            func priceChangePercetage(priceChange: String, coin: CoinModel) -> Double  {
                if pricePercentage == "1h" {
                    return coin.priceChangePercentage1H ?? 0.0
                } else if pricePercentage == "24h" {
                    return coin.priceChangePercentage24H ?? 0.0
                } else if pricePercentage == "7d" {
                    return coin.priceChangePercentage7D ?? 0.0
                } else {
                    return coin.priceChangePercentage30D ?? 0.0
                }
            }
        } else {
            
        }
    }
}
