//
//  GlobalWorkerWorker.swift
//  MarketingCoins
//
//  Created by Gabriel Felix on 03/11/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class GlobalWorkerWorker {
    
    private let dataProvider: GlobalWorkerDataProvider?
    private var completionn: ((Result<GlobalModel?, >) -> Void)
}
