//
//  GlobalValuesWorker.swift
//  MarketingCoins
//
//  Created by Gabriel Felix on 03/11/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class GlobalValuesWorker {
    
    private let dataProvider: GlobalValuesDataProvider?
    private var completion: ((Result<GlobalModel?, CryptocurrenciesError>) -> Void)?
    
    init(dataProvider: GlobalValuesDataProvider = GlobalValuesDataProvider()) {
        self.dataProvider = dataProvider
        self.dataProvider?.delegate = self
    }
    
    func doFetchGlobalValues(completion: @escaping (Result<GlobalModel?, CryptocurrenciesError>) -> Void) {
        self.completion = completion
        dataProvider?.fetchGlobalValues()
    }
}

// MARK: - GlobalValuesDataProviderDelegate
extension GlobalValuesWorker: GlobalValuesDataProviderDelegate {
    
    func success(model: Any) {
        guard let completion = completion else {
            fatalError("Completion not implemented!")
        }
        completion(.success(model as? GlobalModel))
    }
    
    func errorData(_ provider: GenericDataProviderDelegate?, error: Error) {
        guard let completion = completion else {
            fatalError("Completion not implemented!")
        }
        
        // Aqui assumimos que Error possui uma propriedade `errorCode`.
        // Se não possuir, é necessário adaptar.
        let nsError = error as NSError
        switch nsError.code {
        case 500:
            completion(.failure(.internalServerError))
        case 400:
            completion(.failure(.badRequestError))
        case 404:
            completion(.failure(.notFoundError))
        default:
            completion(.failure(.undefinedError))
        }
    }
}
